name: Build and Test
on: push

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      # Setup
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"
      - run: npm install -g yarn
      - run: yarn install

      # Build
      - name: Build
        run: yarn run build

      # Test
      - name: Test
        run: yarn run test
